### ISSUE TITLE
Progress bar does not progress

### ISSUE THREAD

**Issue by Carrolito** [TioFuna/DFLocalizationTool#3]
Hello, I have a problem, download the program to translate the Dwarven fortress into Spanish, since no method has worked for me, but when using the program, it only stays that way, I put the .po files in / localization / Translations but nothing, sorry If I wrote something wrong, I'm using a translator.
http://i.imgur.com/9V8LAR1.png

**Comment by TioFuna** [comment]
Hola!

Vou verificar como está o funcionamento da ferramenta, faz tempo que fiz ela, e em breve te dou um retorno.

Atualmente estou envolvido com outras prioridades e não estou tendo tempo pra dedicar ao DF.

Gracias,

TioFuna


________________________________
De: Carrolito <notifications@github.com>
Enviado: quinta-feira, 17 de agosto de 2017 09:28
Para: TioFuna/DFLocalizationTool
Cc: Subscribed
Assunto: [TioFuna/DFLocalizationTool] Progress bar does not progress (#3)


Hello, I have a problem, download the program to translate the Dwarven fortress into Spanish, since no method has worked for me, but when using the program, it only stays that way, I put the .po files in / localization / Translations but nothing, sorry If I wrote something wrong, I'm using a translator.
http://i.imgur.com/9V8LAR1.png

[http://i.imgur.com/9V8LAR1.png]

**Comment by Carrolito** [comment]
Olá, resolvi o problema de não avançar o bar, mas agora há outro, quando os arquivos "traduzidos" foram criados e colocados nas pastas correspondentes, eu começo o jogo e o Fort Dwarf ainda está em inglês, muito obrigado por responder :D

**Comment by TioFuna** [comment]
Hola,

Pode responder em sua língua nativa que eu uso o tradutor do google, caso necessário.

Minha ferramenta não faz todo o trabalho de traduzir o jogo. Faz somente o que os desenvolvedores permitem, que é traduzir os arquivos de textos disponíveis com o jogo. Logo, muitas coisas não vão estar traduzidas, como a interface do jogo.

Pra uma tradução mais completa, recomendo usar a do 'Insolor', o qual fez uma localização Russa do jogo. E pode ser encontrada no fórum do DF.

Espero ter ajudado.

TioFuna


________________________________
De: Carrolito <notifications@github.com>
Enviado: sexta-feira, 18 de agosto de 2017 03:18
Para: TioFuna/DFLocalizationTool
Cc: Alexandre Hernandes; Comment
Assunto: Re: [TioFuna/DFLocalizationTool] Progress bar does not progress (#3)


Olá, resolvi o problema de não avançar o bar, mas agora há outro, quando os arquivos "traduzidos" foram criados e colocados nas pastas correspondentes, eu começo o jogo e o Fort Dwarf ainda está em inglês, muito obrigado por responder :D
